diffusion:
  type: "all-atom"
  name: "Testaa"
  path: "home/outputs"
  contigs: "50-50/A130-136/20-20"
  pdb: "home/input.pdb"
  iterations: 100
  num_designs: 2
  noise_scale: 1
  substrate: "J1K"

seqdesign:
  rmsd_cutoff: 1
  clash_cutoff: 2
  num_seqs: 4
  model_type: "protein_mpnn"
  relax_design_cycles: 2
  params_file: "home/2PE.params"
  cst_file: "home/constraints.cst"

folding:
  num_recycles: 3
  num_models: 2
  msa_mode: "single_sequence"